import { Metadata } from "next";
import NavigationBar from "../components/navigation-bar";

export const metadata: Metadata = {
  title: {
    template: "%s | learn Next.js",
    default: "...Loading",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavigationBar />
        {children}
      </body>
    </html>
  );
}
