import { Metadata } from "next";
import { ReactNode } from "react";
import NavigationBar from "../components/navigation-bar";
import "./reset.css";
import "./global.css";

export const metadata: Metadata = {
  title: {
    template: "%s | learn Next.js",
    default: "...Loading",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <link rel="preconnect" href="https://youtube.com"></link>
      <body>
        <NavigationBar />
        {children}
      </body>
    </html>
  );
}
